name: Build, run tests, code linting

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Allows you to try different .NET versions for version coverage.
        dotnet-version: [8.0] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        # collect coverage to opencover format and enforce threshold only on master
        run: |
          DOTNET_CLI_TELEMETRY_OPTOUT=1 dotnet test \
            --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=./coverage/ \
            ${{ github.ref == 'refs/heads/master' && '/p:Threshold=80 /p:ThresholdType=line' || '' }}
          
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-opencover
          path: coverage/*.opencover.xml

      - name: Generate HTML report
        if: always()
        run: |
          reportgenerator \
            -reports:coverage/*.opencover.xml \
            -targetdir:coverage-report \
            -reporttypes:HtmlInline_AzurePipelines
          
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage-report
