name: Build, run tests, code linting

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Allows you to try different .NET versions for version coverage.
        dotnet-version: [8.0]
        
    steps:
      - uses: actions/checkout@v4
      - name: Checkout repository
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore
        
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        
      - name: Build
        run: dotnet build --no-restore
    
      - name: Run tests with coverage
        # collect coverage to opencover format and enforce threshold only on master
        run: |
          dotnet test \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            --logger trx

      - name: Generate HTML report
        if: always()
        run: |
          reportgenerator \
            -reports:TestResults/**/coverage.cobertura.xml \
            -targetdir:CoverageReport \
            -reporttypes:HtmlInline;Covertura;TextSummary;MarkdownSummary \
          
      - name: Coverage summary
        run: cat CoverageReport/summary.txt
          
      - name: Fail if coverage is below threshold
        run: |
          threshold=80
          actual=$(grep -Po 'Line coverage.*\K[\d.]+' CoverageReport/summary.txt)
          echo "Actual line coverage: $actual%"
          if (( $(echo "$actual < $threshold" | bc -l) )); then
            echo "❌ Coverage $actual% is below threshold $threshold%"
            exit 1
          fi
